version: '3.8'

services:
  # 1. The Database
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ecommerce_inventory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. The Job Queue Store (Required for BullMQ)
  redis:
    image: redis:alpine
    container_name: ecommerce_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata: